<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Timas Application</title>

  <?php echo $this->headLink()->appendStylesheet('media/css/bootstrap.css') ?>
</head>
<body>
<div id="header" class="container">
<?php echo $this->render('_header.phtml') ?>
<?php echo $this->layout()->content ?>
<?php //echo $this->render('_footer.phtml') ?>
</div>
 

 
</body>
</html>
